name: Android CI

on:
  push:
    branches: [ "art" ]
  pull_request:
    branches: [ "art" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: snapshot
        path: |
          ${{ github.workspace }}/app/build/outputs/apk
          ${{ github.workspace }}/app/build/outputs/mapping
